x-common-log-config: &default_config
  networks:
    - nosql_pipeline_network

services:
  notebook:
    build: ../docker/notebook
    container_name: notebook
    <<: *default_config
    restart: always
    volumes:
      - ../mnt/notebook:/app/
    ports:
      - "8888:8888"

  mongodb:
    image: mongo:6.0
    container_name: mongo_container
    <<: *default_config
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  nosql_pipeline_network:
    name: nosql_pipeline_network
