x-common-log-config: &default_config
  networks:
    - nosql_pipeline_network

services:
  notebook:
    build: ../docker/notebook
    container_name: notebook
    <<: *default_config
    restart: always
    volumes:
      - ../mnt/notebooks:/app/
    ports:
      - "8888:8888"
  
networks:
  nosql_pipeline_network:
    name: nosql_pipeline_network
