x-common-log-config: &default_config
  networks:
    - nosql_pipeline_network

services:
  notebook:
    build: ../docker/notebook
    container_name: notebook
    <<: *default_config
    restart: always
    env_file:
      - .env
    volumes:
      - ../mnt/notebook:/app/
      - ../mnt/python_scripts:/app/python/
    ports:
      - "8888:8888"

  mongodb:
    image: mongo:6.0
    container_name: mongo_container
    <<: *default_config
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    <<: *default_config
    restart: always
    env_file:
      - .env
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin      
      ME_CONFIG_BASICAUTH_PASSWORD: admin123 

volumes:
  mongo_data:

networks:
  nosql_pipeline_network:
    name: nosql_pipeline_network
